version: '3.3'

services:
    mysqldb:
        image: mysql:5.7.27
        user: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "4306:3306"

    app:
        depends_on:
            - mysqldb
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
